#ifndef ENGINE_H
#define ENGINE_H

enum {
	ENGINE_IMSG_ERROR,
	ENGINE_IMSG_DOWNLOAD,
	ENGINE_IMSG_DOWNLOAD_OVER,
	ENGINE_IMSG_FILE,
	ENGINE_IMSG_FILE_STDOUT,
	ENGINE_IMSG_NEED_PATH,
	ENGINE_IMSG_PATH,
	ENGINE_IMSG_PROGRESS,
	ENGINE_IMSG_REDIRECT,
	ENGINE_IMSG_REDIRECT_OVER,
};

#define ENGINE_ERROR_MAX 128
#define ENGINE_URL_MAX 2000

struct engine_progress {
	long long content_length;
	long long total_read;
	unsigned int percent;
};

#endif /* ENGINE_H */
